export const carMakes = [
  "Camry",
  "Corolla",
  "RAV4",
  "Highlander",
  "Prius",
  "Avalon",
  "Sienna",
  "Tacoma",
  "Tundra",
  "4Runner",
  "Sequoia",
  "Land Cruiser",
  "GR Supra",
  "GR86",
  "C-HR",
  "Venza",
  "Mirai",
  "Civic",
  "Accord",
  "CR-V",
  "Pilot",
  "HR-V",
  "Passport",
  "Ridgeline",
  "Insight",
  "Fit",
  "Odyssey",
  "Element",
  "S2000",
  "NSX",
  "F-150",
  "Mustang",
  "Explorer",
  "Escape",
  "Edge",
  "Expedition",
  "Bronco",
  "Ranger",
  "Transit",
  "Focus",
  "Fusion",
  "Taurus",
  "EcoSport",
  "Flex",
  "Silverado",
  "Equinox",
  "Malibu",
  "Traverse",
  "Tahoe",
  "Suburban",
  "Camaro",
  "Corvette",
  "Blazer",
  "Trax",
  "Sonic",
  "Cruze",
  "Impala",
  "Volt",
  "Bolt",
  "C-Class",
  "E-Class",
  "S-Class",
  "A-Class",
  "CLA",
  "GLA",
  "GLB",
  "GLC",
  "GLE",
  "GLS",
  "AMG GT",
  "SL",
  "G-Class",
  "EQS",
  "EQE",
  "A3",
  "A4",
  "A6",
  "A8",
  "Q3",
  "Q5",
  "Q7",
  "Q8",
  "TT",
  "R8",
  "e-tron",
  "e-tron GT",
  "RS3",
  "RS4",
  "RS6",
  "RS7",
  "Altima",
  "Sentra",
  "Rogue",
  "Murano",
  "Pathfinder",
  "Armada",
  "Frontier",
  "Titan",
  "370Z",
  "GT-R",
  "Leaf",
  "Versa",
  "Maxima",
  "NV200",
  "Elantra",
  "Sonata",
  "Tucson",
  "Santa Fe",
  "Palisade",
  "Kona",
  "Venue",
  "Accent",
  "Genesis",
  "Ioniq",
  "Nexo",
  "Veloster",
  "Forte",
  "Optima",
  "Sportage",
  "Sorento",
  "Telluride",
  "Soul",
  "Rio",
  "Stinger",
  "Niro",
  "EV6",
  "Carnival",
  "Sedona",
  "Jetta",
  "Passat",
  "Tiguan",
  "Atlas",
  "Golf",
  "Beetle",
  "Arteon",
  "ID.4",
  "ID.Buzz",
  "CC",
  "Touareg",
  "Impreza",
  "Legacy",
  "Outback",
  "Forester",
  "Ascent",
  "WRX",
  "BRZ",
  "Crosstrek",
  "Mazda3",
  "Mazda6",
  "CX-3",
  "CX-5",
  "CX-9",
  "MX-5 Miata",
  "CX-30",
  "IS",
  "ES",
  "GS",
  "LS",
  "NX",
  "RX",
  "GX",
  "LX",
  "LC",
  "RC",
  "UX",
  "ILX",
  "TLX",
  "RLX",
  "RDX",
  "MDX",
  "NSX",
  "Integra",
  "Q50",
  "Q60",
  "Q70",
  "QX50",
  "QX60",
  "QX80",
  "G37",
  "FX35",
  "ATS",
  "CTS",
  "XTS",
  "XT4",
  "XT5",
  "XT6",
  "Escalade",
  "CT4",
  "CT5",
  "CT6",
  "MKZ",
  "Continental",
  "Corsair",
  "Nautilus",
  "Aviator",
  "Navigator",
  "XE",
  "XF",
  "XJ",
  "F-PACE",
  "E-PACE",
  "I-PACE",
  "F-TYPE",
  "Range Rover",
  "Range Rover Sport",
  "Range Rover Evoque",
  "Range Rover Velar",
  "Discovery",
  "Discovery Sport",
  "Defender",
  "911",
  "Cayenne",
  "Macan",
  "Panamera",
  "Taycan",
  "Boxster",
  "Cayman",
  "718",
  "Model S",
  "Model 3",
  "Model X",
  "Model Y",
  "Roadster",
  "Cybertruck",
  "S60",
  "S90",
  "V60",
  "V90",
  "XC40",
  "XC60",
  "XC90",
  "G70",
  "G80",
  "G90",
  "GV70",
  "GV80",
  "Electrified G80",
];

// Car makes and their models
export const carData = {
  Toyota: {
    models: [
      "Camry",
      "Corolla",
      "RAV4",
      "Highlander",
      "Prius",
      "Avalon",
      "Sienna",
      "Tacoma",
      "Tundra",
      "4Runner",
      "Sequoia",
      "Land Cruiser",
      "GR Supra",
      "GR86",
      "C-HR",
      "Venza",
      "Mirai",
    ],
    priceRange: { min: 20000, max: 80000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Honda: {
    models: [
      "Civic",
      "Accord",
      "CR-V",
      "Pilot",
      "HR-V",
      "Passport",
      "Ridgeline",
      "Insight",
      "Fit",
      "Odyssey",
      "Element",
      "S2000",
      "NSX",
    ],
    priceRange: { min: 18000, max: 75000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Ford: {
    models: [
      "F-150",
      "Mustang",
      "Explorer",
      "Escape",
      "Edge",
      "Expedition",
      "Bronco",
      "Ranger",
      "Transit",
      "Focus",
      "Fusion",
      "Taurus",
      "EcoSport",
      "Flex",
    ],
    priceRange: { min: 22000, max: 90000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Chevrolet: {
    models: [
      "Silverado",
      "Equinox",
      "Malibu",
      "Traverse",
      "Tahoe",
      "Suburban",
      "Camaro",
      "Corvette",
      "Blazer",
      "Trax",
      "Sonic",
      "Cruze",
      "Impala",
      "Volt",
      "Bolt",
    ],
    priceRange: { min: 20000, max: 120000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  BMW: {
    models: [
      "3 Series",
      "5 Series",
      "7 Series",
      "X1",
      "X3",
      "X5",
      "X7",
      "Z4",
      "i3",
      "i4",
      "iX",
      "M3",
      "M5",
      "M8",
      "X4",
      "X6",
    ],
    priceRange: { min: 35000, max: 150000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  "Mercedes-Benz": {
    models: [
      "C-Class",
      "E-Class",
      "S-Class",
      "A-Class",
      "CLA",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "AMG GT",
      "SL",
      "G-Class",
      "EQS",
      "EQE",
    ],
    priceRange: { min: 40000, max: 200000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Audi: {
    models: [
      "A3",
      "A4",
      "A6",
      "A8",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "R8",
      "e-tron",
      "e-tron GT",
      "RS3",
      "RS4",
      "RS6",
      "RS7",
    ],
    priceRange: { min: 30000, max: 180000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Nissan: {
    models: [
      "Altima",
      "Sentra",
      "Rogue",
      "Murano",
      "Pathfinder",
      "Armada",
      "Frontier",
      "Titan",
      "370Z",
      "GT-R",
      "Leaf",
      "Versa",
      "Maxima",
      "NV200",
    ],
    priceRange: { min: 15000, max: 120000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Hyundai: {
    models: [
      "Elantra",
      "Sonata",
      "Tucson",
      "Santa Fe",
      "Palisade",
      "Kona",
      "Venue",
      "Accent",
      "Genesis",
      "Ioniq",
      "Nexo",
      "Veloster",
    ],
    priceRange: { min: 16000, max: 60000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Kia: {
    models: [
      "Forte",
      "Optima",
      "Sportage",
      "Sorento",
      "Telluride",
      "Soul",
      "Rio",
      "Stinger",
      "Niro",
      "EV6",
      "Carnival",
      "Sedona",
    ],
    priceRange: { min: 15000, max: 55000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Volkswagen: {
    models: [
      "Jetta",
      "Passat",
      "Tiguan",
      "Atlas",
      "Golf",
      "Beetle",
      "Arteon",
      "ID.4",
      "ID.Buzz",
      "CC",
      "Touareg",
    ],
    priceRange: { min: 20000, max: 70000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Subaru: {
    models: [
      "Impreza",
      "Legacy",
      "Outback",
      "Forester",
      "Ascent",
      "WRX",
      "BRZ",
      "Crosstrek",
    ],
    priceRange: { min: 22000, max: 50000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Mazda: {
    models: ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5 Miata", "CX-30"],
    priceRange: { min: 20000, max: 45000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Lexus: {
    models: ["IS", "ES", "GS", "LS", "NX", "RX", "GX", "LX", "LC", "RC", "UX"],
    priceRange: { min: 35000, max: 100000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Acura: {
    models: ["ILX", "TLX", "RLX", "RDX", "MDX", "NSX", "Integra"],
    priceRange: { min: 30000, max: 80000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Infiniti: {
    models: ["Q50", "Q60", "Q70", "QX50", "QX60", "QX80", "G37", "FX35"],
    priceRange: { min: 35000, max: 90000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Cadillac: {
    models: [
      "ATS",
      "CTS",
      "XTS",
      "XT4",
      "XT5",
      "XT6",
      "Escalade",
      "CT4",
      "CT5",
      "CT6",
    ],
    priceRange: { min: 35000, max: 120000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Lincoln: {
    models: [
      "MKZ",
      "Continental",
      "Corsair",
      "Nautilus",
      "Aviator",
      "Navigator",
    ],
    priceRange: { min: 35000, max: 100000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Jaguar: {
    models: ["XE", "XF", "XJ", "F-PACE", "E-PACE", "I-PACE", "F-TYPE"],
    priceRange: { min: 40000, max: 120000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  "Land Rover": {
    models: [
      "Range Rover",
      "Range Rover Sport",
      "Range Rover Evoque",
      "Range Rover Velar",
      "Discovery",
      "Discovery Sport",
      "Defender",
    ],
    priceRange: { min: 45000, max: 150000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Porsche: {
    models: [
      "911",
      "Cayenne",
      "Macan",
      "Panamera",
      "Taycan",
      "Boxster",
      "Cayman",
      "718",
    ],
    priceRange: { min: 50000, max: 200000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Tesla: {
    models: [
      "Model S",
      "Model 3",
      "Model X",
      "Model Y",
      "Roadster",
      "Cybertruck",
    ],
    priceRange: { min: 40000, max: 150000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Volvo: {
    models: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
    priceRange: { min: 35000, max: 80000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
  Genesis: {
    models: ["G70", "G80", "G90", "GV70", "GV80", "Electrified G80"],
    priceRange: { min: 35000, max: 80000 },
    popularYears: [2020, 2021, 2022, 2023, 2024],
  },
};

// Body types with realistic distribution
export const bodyTypes = [
  { name: "Sedan", weight: 0.25 },
  { name: "SUV", weight: 0.3 },
  { name: "Hatchback", weight: 0.15 },
  { name: "Coupe", weight: 0.1 },
  { name: "Convertible", weight: 0.05 },
  { name: "Wagon", weight: 0.08 },
  { name: "Truck", weight: 0.07 },
];

// Colors with realistic distribution
export const colors = [
  { name: "White", weight: 0.2 },
  { name: "Black", weight: 0.18 },
  { name: "Silver", weight: 0.15 },
  { name: "Gray", weight: 0.12 },
  { name: "Red", weight: 0.1 },
  { name: "Blue", weight: 0.08 },
  { name: "Brown", weight: 0.05 },
  { name: "Green", weight: 0.04 },
  { name: "Gold", weight: 0.03 },
  { name: "Orange", weight: 0.02 },
  { name: "Yellow", weight: 0.02 },
  { name: "Purple", weight: 0.01 },
];

// Fuel types
export const fuelTypes = [
  { name: "Gasoline", weight: 0.7 },
  { name: "Hybrid", weight: 0.15 },
  { name: "Electric", weight: 0.1 },
  { name: "Diesel", weight: 0.05 },
];

// Transmissions
export const transmissions = [
  { name: "Automatic", weight: 0.8 },
  { name: "Manual", weight: 0.15 },
  { name: "CVT", weight: 0.05 },
];

export const faqItems = [
  {
    question: "How does the test drive booking work?",
    answer:
      "Simply find a car you're interested in, click the 'Test Drive' button, and select an available time slot. Our system will confirm your booking and provide all necessary details.",
  },
  {
    question: "Can I search for cars using an image?",
    answer:
      "Yes! Our AI-powered image search lets you upload a photo of a car you like, and we'll find similar models in our inventory.",
  },
  {
    question: "Are all cars certified and verified?",
    answer:
      "All cars listed on our platform undergo a verification process. We are a trusted dealerships and verified private seller.",
  },
  {
    question: "What happens after I book a test drive?",
    answer:
      "After booking, you'll receive a confirmation email with all the details. We will also contact you to confirm and provide any additional information.",
  },
];
